- name: Add Poshbot Module
  win_psmodule:
    name: PoshBot
    state: present
- name: Create Poshbot Directory
  win_file:
    path: '{{ item }}'
    state: Directory
  with_items:
    - 'c:\poshbot'
    - 'c:\poshbot\plugins'
    - 'c:\poshbot\logs'
- name: Copy config template
  template:
    src: templates/config.j2
    dest: 'c:\poshbot\config.psd1'